version: '3.4'

services:
  lc.backend.api:
    build:
      context: .
      dockerfile: LC.Backend.Api/Dockerfile
    ports:
        - '5000:80'
    depends_on:
        - rabbitmq

  lc.services.identity:
    build:
      context: .
      dockerfile: LC.Services.Identity/Dockerfile
    ports:
        - '5001:5001'
        - '5005:80'
    links:
        - rabbitmq
        - mongo
    hostname: identityservice

  lc.services.logging:
    build:
      context: .
      dockerfile: LC.Services.Logging/Dockerfile
    ports:
        - '5002'
    links:
        - rabbitmq
        - mongo

  rabbitmq:
    container_name: 'rabbitmq'
    image: rabbitmq:3.6.5-management
    ports:
      - '5672:5672'
      - '15672:15672'

  mongo:
    container_name: 'mongo'
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - '27017:27017'


